version: "3.9"

services:
  web:
    build: ./webapp
    ports:
      - "5000:5000"
    depends_on:
      - redis

  nginx:
    build: ./static_site
    ports:
      - "8080:80"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
